apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: ifost-website

build:
  artifacts:
    - image: ifost-website
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - ../cloudops/apps/ifost-website

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: ifost-website
    namespace: ifost-website
    port: 80
    localPort: 3000

profiles:
  - name: release
    build:
      tagPolicy:
        envTemplate:
          template: "v0.1.0"
      local:
        push: true
